### ISSUE TITLE
CORS api with manala and nginx

### ISSUE THREAD

**Issue by maximecolin** [maximecolin/technical#15]
Add CORS header in a file:

```yml
nginx_config:
    # Access Control Headers
    - file:     app_access_control
      config:
        - add_header: "Access-Control-Allow-Origin \"*\" always"
        - add_header: "Access-Control-Allow-Methods \"GET, POST, PUT, PATCH, DELETE, OPTIONS\" always"
        - add_header: "Access-Control-Allow-Headers \"Authorization, Content-Type, Accept-Encoding, Cache-Control\" always"
        - add_header: "Access-Control-Allow-Credentials \"true\" always"
        - if ($request_method = OPTIONS):
          - return: 204
```

Then include the file in your servers:

```
- include:     conf.d/app_access_control
```

For example:

```yml
nginx_configs:
    - file: app.conf
      config:
        - server:
          - server_name: "{{ app.host }}"
          #- server_name: "*.ngrok.io"
          - root:        "{{ app.dir }}{{ app.dir_release }}/web"
          - access_log:  "{{ app.log_dir }}/nginx.access.log"
          - error_log:   "{{ app.log_dir }}/nginx.error.log"
          - include:     conf.d/app_gzip
          - include:     conf.d/app_access_control
          - location /:
            - try_files: $uri /app.php$is_args$args
          - location ~ ^/(app(_[-\w]+)?)\.php(/|$):
            - include: conf.d/app_php_fpm
            #- internal;
```
